techbangla/techbangla/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('techblog.urls')),
    path('account/', include('techuser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techbangla/techblog/urls.py
from django.urls import path
from techblog import views

app_name = 'tech_blog'

urlpatterns = [
    path('', views.IndexBlogView.as_view(), name='index'),
    path('blog-content/<slug:slug_name>', views.BlogView.as_view(), name='blog-content'),
    path('add-new/', views.AddNewView.as_view(), name='add-new'),
    path('edit-blog/<slug:slug_name>', views.EditBlogView.as_view(), name='edit-blog'),
    path('all/<name>/', views.AllBlogsView.as_view(), name='all-blogs'),
    path('like/<slug:slug_name>/', views.LikeView, name='like'),
]

techbangla/techuser/urls.py
from django.urls import path
from techuser import views

app_name = "tech_user"

urlpatterns = [
    path('', views.ownprofile, name='ownprofile'),
    path('authorprofile/<username>', views.authorprofile, name='authorprofile'),
    path('registration/', views.registrationview, name='registration'),
    path('login/', views.loginview, name='login'),
    path('logouturl/', views.logoutview, name='logouturl'),
    path('user-settings/', views.settingsview, name='user-settings'),
    path('basic-settings/', views.basicsetting, name='basic-settings'),
    path('other-settings/', views.othersetting, name='other-settings'),
    path('profilepic-settings/', views.addprofilepic, name='profilepic-settings'),
    path('passchange/', views.changepass, name='passchange'),
]

techbangla/techblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=25, unique=True)

    def has_subcategories(self):
        return self.subcategory.count()

    def __str__(self):
        return self.category_name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategory')
    subcategory_name = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return f"{self.category.category_name} - {self.subcategory_name}"


class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_blog")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, related_name='sub_category')
    blogtitle = models.CharField(max_length=250, verbose_name="BLOG TITLE")
    blogcontent = models.TextField(verbose_name="BLOG CONTENT")
    blogimg = models.ImageField(upload_to="blog_image", verbose_name="ADD BLOG IMAGE")
    slug = models.SlugField(max_length=250, unique=True)
    published_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blogtitle

    # def get_absolute_url(self):
    #     return reverse('tech_blog:blog-content', kwargs={'slug_name': self.slug})


class BlogComment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ('-comment_date',)


class BlogLikes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_like')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')

techbangla/techblog/forms.py
from django import forms
from techblog.models import Blog, BlogComment


class BLogForm(forms.ModelForm):
    blogimg = forms.ImageField(label='Add Image', widget=forms.FileInput(
        attrs={'class': 'input-form', 'type': 'file', 'accept': 'image/jpeg'}))

    class Meta:
        model = Blog
        fields = ('category', 'sub_category', 'blogtitle', 'blogcontent', 'blogimg',)


class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea, label='')

    class Meta:
        model = BlogComment
        fields = ('comment',)

techbangla/techblog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, DetailView, ListView, UpdateView
from techblog.models import Blog, BlogLikes, BlogComment
from techblog.forms import BLogForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from django.shortcuts import reverse
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


# Create your views here.
class IndexBlogView(ListView):
    model = Blog
    context_object_name = 'blogs'
    template_name = "index.html"


class BlogView(DetailView, CreateView):
    model = Blog
    form_class = CommentForm
    # slug_field = 'slug_name'
    slug_url_kwarg = 'slug_name'
    template_name = "blog-content.html"

    def form_valid(self, form):
        comment_obj = form.save(commit=False)
        slug = str(self.request.path).split('/')[2]
        blog = Blog.objects.get(slug=slug)
        comment_obj.blog = blog
        comment_obj.user = self.request.user
        comment_obj.save()
        return HttpResponseRedirect(reverse('tech_blog:blog-content', kwargs={'slug_name': slug}))


@login_required
def LikeView(request, slug_name):
    blog = Blog.objects.get(slug=slug_name)
    user = request.user

    already_liked = BlogLikes.objects.filter(blog=blog, user=user)
    if not already_liked:
        like_post = BlogLikes(blog=blog, user=user)
        like_post.save()
    return HttpResponseRedirect(reverse('tech_blog:blog-content', kwargs={'slug_name': slug_name}))


class AllBlogsView(ListView):
    model = Blog
    context_object_name = 'blogs'
    template_name = "all-blogs.html"
    # extra_context = {
    #     'pathss': 'Test'
    # }

    # Class based context passing
    def get_context_data(self, **kwargs):
        context = super(AllBlogsView, self).get_context_data(**kwargs)
        context['path'] = str(self.request.path).split('/')[2]
        return context

    # def get_queryset(self):
    #     qs = super(AllBlogsView, self).get_queryset()
    #     return qs.filter(sub_category=self.kwargs.get('name'))


class AddNewView(LoginRequiredMixin, CreateView):
    model = Blog
    # fields = ('category', 'sub_category', 'blogtitle', 'blogcontent', 'blogimg',)
    form_class = BLogForm
    template_name = "add-new.html"

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.user = self.request.user
        title = blog_obj.blogtitle
        blog_obj.slug = title.replace(' ', '-') + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('tech_blog:index'))


class EditBlogView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('category', 'sub_category', 'blogtitle', 'blogcontent', 'blogimg')
    slug_url_kwarg = 'slug_name'
    success_url = reverse_lazy('tech_blog:blog-content')
    template_name = 'add-new.html'

    # This is one method to reverse to previous page, another method is get_absolute_url in model.py page
    def get_success_url(self):
        return reverse('tech_blog:blog-content', kwargs={'slug_name': self.object.slug})


def custom_error_404(request, exception):
    return render(request, '../templates/404.html', {})

techbangla/techblog/templates/add-new.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}Add New Blog{% endblock %}
{% block body_block %}
<div class="new-blog-section">
{% if blog.user == user %}
<div class="text-separation mb-5">
            <div class="text-separator-content border-bottom-2">
                <h3><b>UPDATE</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
    {% else %}
<div class="text-separation mb-5">
            <div class="text-separator-content border-bottom-2">
                <h3><b>ADD NEW</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
    {% endif %}

    <form method="POST" action="" enctype="multipart/form-data">
        {{ form|crispy }}
{#        <label for="blogcat" class="label">BLOG CATEGORY</label>#}
{#        <select name="blogcat" id="blogcat" class=" input-form">#}
{#            <option value="" selected>Select</option>#}
{#            <optgroup label="Programming">#}
{#                <option value="Java">Java</option>#}
{#                <option value="Python">Python</option>#}
{#                <option value="Javascript">Javascript</option>#}
{#            </optgroup>#}
{#            <optgroup label="Framework">#}
{#                <option value="Java">Java</option>#}
{#                <option value="Python">Python</option>#}
{#                <option value="Javascript">Javascript</option>#}
{#            </optgroup>#}
{#        </select>#}
{#        <label for="blogtitle" class="label">BLOG TITLE</label>#}
{#        <input type="text" name="blogtitle" id="blogtitle" class="input-form">#}
{#        <label for="blogcontent" class="label">BLOG CONTENT</label>#}
{#        <textarea name="blogcontent" id="blogcontent" cols="30" rows="10" class="textarea"></textarea>#}
{#        <label for="blogimg" class="label">ADD Image</label>#}
{#        <input type="file" name="blogimg" id="blogimg" class="input-form" accept="image/jpeg">#}
        {% csrf_token %}
        <div class="sep"></div>
        {% if blog.user == user %}
        <input type="submit" value="UPDATE" class="btn login-btn">
        {% else %}
        <input type="submit" value="CREATE" class="btn login-btn">
        {% endif %}
    </form>
</div>
{% endblock %}

techbangla/techblog/templates/all-blogs.html
{% extends "base.html" %}
{% block title_block %}All Blogs in Categories{% endblock %}
{% load static %}
{% load my_filter %}
{% block body_block %}
    <div class="d-flex align-items-center justify-content-center">
        <div class="grid">
            {% for blog in blogs %}
                {% if path == blog.sub_category.subcategory_name|replacespace %}
                    <div class="blog">
                <div class="blog-img">
                    <img src="{{ blog.blogimg.url }}" alt="" class="img-fluid">
                </div>
                <br>
                <div class="tag d-flex">
                    <a href="{% url "tech_blog:all-blogs" name=blog.category|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ blog.category }}</b></h6>
                    </a>
                    <span>&nbsp; &nbsp;</span>
                    <a href="{% url "tech_blog:all-blogs" name=blog.sub_category.subcategory_name|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ blog.sub_category.subcategory_name }}</b></h6>
                    </a>
                </div>
                <br>
                <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}">
                    <h5>{{ blog.blogtitle }}</h5>
                </a>
                <div class="blog-summery">
                    <p>{{ blog.blogcontent|range_filter }}
                        <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}">Read More...</a></p>
                </div>
            </div>
                    {% elif path == blog.category.category_name|replacespace %}
                    <div class="blog">
                <div class="blog-img">
                    <img src="{{ blog.blogimg.url }}" alt="" class="img-fluid">
                </div>
                <br>
                <div class="tag d-flex">
                    <a href="{% url "tech_blog:all-blogs" name=blog.category|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ blog.category }}</b></h6>
                    </a>
                    <span>&nbsp; &nbsp;</span>
                    <a href="{% url "tech_blog:all-blogs" name=blog.sub_category.subcategory_name|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ blog.sub_category.subcategory_name }}</b></h6>
                    </a>
                </div>
                <br>
                <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}">
                    <h5>{{ blog.blogtitle }}</h5>
                </a>
                <div class="blog-summery">
                    <p>{{ blog.blogcontent|range_filter }}
                        <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}">Read More...</a></p>
                </div>
            </div>
                {% endif %}

            {% endfor %}
        </div>
    </div>
{% endblock %}

techbangla/techblog/templates/blog-content.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Blog Title Goes Here {% endblock %}
{% block body_block %}
    <div class="">
        <div class="p-lg-5 text-center">
            <div class="blog-cover">
                <img class="border-radius" src="{{ blog.blogimg.url }}" alt="">
                <div class="blog-title-overlay border-radius d-flex align-items-center justify-content-center flex-column p-sm-1 p-md-1 px-1">
                    <h2><b>{{ blog.blogtitle }}</b></h2>
                    <p><i>{{ blog.user.first_name }} {{ blog.user.last_name }}</i></p>
                </div>
            </div>
        </div>
        <div class="blog-content px-lg-5">
            <div class="px-lg-5">
                {% if user == blog.user %}
                    <a href="{% url "tech_blog:edit-blog" slug_name=blog.slug %}" class="btn btn-primary">Edit</a>
                {% endif %}
                <div class="blog-content-l-c text-start my-4">{{ blog.user.first_name }}:&nbsp;{{ blog.published_date }}
                    <br> <i
                            class="fal fa-thumbs-up"></i> {{ blog.blog_like.count }} | <i class="fal fa-comment-alt"></i> {{ blog.blog_comment.count }}
                </div>
                <p>Updated On: {{ blog.edit_date }}</p>
                <p class="">{{ blog.blogcontent }}</p>
            </div>
            <div class="l-c-section p-lg-5">
                <p><a href="{% url "tech_blog:like" slug_name=blog.slug %}"><i class="fal fa-thumbs-up"></i></a>: {{ blog.blog_like.count }}</p>
                <div class="blog-author-info mb-3 border-radius">
                    <div class="row p-5">
                        <div class="col-lg-2 author-img d-flex align-items-center justify-content-center">
                            {% if blog.user.user_profile.profile_pic %}
                            <img src="{{ blog.user.user_profile.profile_pic.url }}" alt="" class="rounded-circle" width="120"
                                 height="120">
                            {% else %}
                            <img src="{% static "images/fox.jpg" %}" alt="" class="rounded-circle" width="120"
                                 height="120">
                            {% endif %}
                        </div>
                        <div class="col-lg-9 author-info d-flex flex-column justify-content-lg-center align-items-lg-start align-items-sm-center ms-lg-4 ms-md-0 ms-sm-0 mt-md-3">
                            <b><a href="{% url "tech_user:authorprofile" username=blog.user.username %}">{{ blog.user.first_name }} {{ blog.user.last_name }}</a></b>
                            <p>{{ blog.user.user_profile.about }}</p>
                            <p>
                                <a href="{{ blog.user.user_profile.website }}"><i class="fab fa fa-globe-asia px-1"></i></a>
                                <a href="{{ blog.user.user_profile.facebook }}"><i
                                        class="fab fa-facebook-f px-1"></i></a>
                                <a href="{{ blog.user.user_profile.twitter }}"><i class="fab fa-twitter px-1"></i></a>
                                <a href="{{ blog.user.user_profile.linkedin }}"><i class="fab fa-linkedin px-1"></i></a>
                                <a href="{{ blog.user.user_profile.github }}"><i class="fab fa-github px-1"></i></a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="blog-all-comments">
                    <div class="text-separation">
                        <div class="text-separator-content border-bottom-2">
                            <h3><b>{{ blog.blog_comment.count }} COMMENTS</b></h3>
                        </div>
                        <div class="text-separator"></div>
                    </div>
                    <br>
                    <br>
                    {% for comment in blog.blog_comment.all %}
                        <div>
                        <div class="blog-comment row p-2">
                            <div class="col-lg-2 author-img d-flex align-items-center justify-content-lg-center justify-content-md-start justify-content-sm-start justify-content-start">
                                {% if comment.user.user_profile.profile_pic %}
                                <img src="{{ comment.user.user_profile.profile_pic.url }}" alt="" class="rounded-circle" width="120" height="120">
                                {% else %}
                                <img src="{% static "images/fox.jpg" %}" alt="" class="rounded-circle" width="120" height="120">
                                {% endif %}
                            </div>
                            <div class="col-lg-9 author-info d-flex flex-column justify-content-lg-center align-items-lg-start  ms-lg-4 ms-md-0 ms-sm-0 mt-md-3">
                                {% if comment.user.first_name or comment.user.last_name %}
                                <b><a href="{% url "tech_user:authorprofile" username=comment.user.username %}">{{ comment.user.first_name }} {{ comment.user.last_name }}</a></b>
                                {% else %}
                                <b><a href="{% url "tech_user:authorprofile" username=comment.user.username %}">{{ comment.user.username }}</a></b>
                                {% endif %}
                                <p>{{ comment.comment }}</p>
                                <em>{{ comment.comment_date }}</em>
                            </div>
                        </div>
                        <hr>
                    </div>
                    {% endfor %}

                </div>

                <div class="comment-section blog-author-info p-5 border-radius">
                    <div class="text-separation mb-5">
                        <div class="text-separator-content border-bottom-2">
                            <h3><b>ADD COMMENT</b></h3>
                        </div>
                        <div class="text-separator"></div>
                    </div>
                    <form class="form" method="POST">
                        {{ form|crispy }}
                        <br>
                        {% csrf_token %}
                        <input type="submit" value="COMMENT" class="btn border-radius btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

techbangla/techblog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}
{% block title_block %} HomePage - TechBangla {% endblock %}
{% block body_block %}
    {#    Slider Section#}
    <div class="slider">
        <div class="slider-class">
            {% for blog in blogs %}
                <div>
                <div class="row d-flex justify-content-center align-items-center">
                    <div class="col-lg-8 col-md-6 col-sm-12 col-12 px-sm-3 px-3">
                        <div class="banner-img-div banner-img">
                            <img src="{{ blog.blogimg.url }}" alt="" class="img-fluid border-radius">
                            <div class="overlay">
                                <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}"><i id="myButton" class="fal fa-book-reader"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 col-12 banner-text py-5">
                        <h6 class="h6-slider"><span><a href="{% url "tech_blog:all-blogs" name=blog.category.category_name|lower|replacespace %}">{{ blog.category.category_name }}</a></span>, <span><a href="{% url "tech_blog:all-blogs" name=blog.sub_category.subcategory_name|lower|replacespace %}">{{ blog.sub_category.subcategory_name }}</a></span></h6>
                        <h2 class="pe-3">{{ blog.blogtitle}}</h2>
                        <p class="pe-3">{{ blog.blogcontent|range_filter }} <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}">Read More...</a></p>
                        <p class="blog-author-banner">Nahidujjaman:25 December 2020 | <i class="fal fa-thumbs-up"></i>
                            {{ blog.blog_like.count }}
                            | <i class="fal fa-comment-alt"></i> {{ blog.blog_comment.count }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {#    Latest Blogs#}
    <div class="latest-blogs-section">
        <div class="text-separation">
            <div class="text-separator"></div>
            <div class="text-separator-content">
                <h3 class="px-3"><b>Latest Blogs</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
        <br>
        <div class="latest-blogs row">
            {% for blog in blogs %}
                <div class="col-lg-4 col-md-4 col-sm-6 col-12 mb-4">
                <div class=" latest-blogs-img-div">
                    <img src="{{ blog.blogimg.url }}" class="img-fluid border-radius" alt="">
                    <div class="overlays">
                        <div class="overlays-content">
                            <h6 class="h6-latest"><span><a href="{% url "tech_blog:all-blogs" name=blog.category.category_name|lower|replacespace %}">{{ blog.category.category_name }}</a></span>, <span><a href="{% url "tech_blog:all-blogs" name=blog.sub_category.subcategory_name|lower|replacespace %}">{{ blog.sub_category.subcategory_name }}</a></span>
                            </h6>
                            <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}"><h2>{{ blog.blogtitle}}</h2></a>
                            <p class="blog-author-latest">{{ blog.user.first_name }}: {{ blog.published_date}} | <i
                                    class="fal fa-thumbs-up"></i> {{ blog.blog_like.count }}
                                | <i class="fal fa-comment-alt"></i> {{ blog.blog_comment.count }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {#    Popular Blogs#}
    <div class="popular-blogs-section">
        <div class="text-separation">
            <div class="text-separator"></div>
            <div class="text-separator-content">
                <h3 class="px-3"><b>Popular Blogs</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
        <br>
        <div class="popular-blogs row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-12 mb-4 popular-blogs-col">
                <div class="popular-blogs-img-div">
                    <img src="{% static "images/11.jpg" %}" class="img-fluid border-radius" alt="">
                    <div class="popular-overlays">
                        <div class="popular-overlays-content">
                            <h6 class="h6-latest"><span><a href="">DESIGN</a></span>, <span><a href="">ART</a></span>
                            </h6>
                            <a href=""><h2>Blog Title that is very very very Big</h2></a>
                            <p class="blog-author-latest">Nahidujjaman:25 December 2020 | <i
                                    class="fal fa-thumbs-up"></i> 5
                                | <i class="fal fa-comment-alt"></i> 10</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-12 mb-4 popular-blogs-col popular-blogs-slider">
                {% for blog in blogs %}
                    <div class="">
                    <hr>
                    <a href="{% url "tech_blog:blog-content" slug_name=blog.slug %}">
                        <div class="popular-blogs-slider-div border-radius">
                            <div class="row d-flex align-items-center">
                                <div class="col-2">
                                    <img src="{{ blog.blogimg.url }}" class="rounded-circle" alt="">
                                </div>
                                <div class="col-8">
                                    <h4>{{ blog.blogtitle}}</h4>
                                    <p>{{ blog.user.first_name }}: {{ blog.published_date }} | <i class="fal fa-thumbs-up"></i> {{ blog.blog_like.count }}
                                        | <i class="fal fa-comment-alt"></i> {{ blog.blog_comment.count }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                    <hr>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>


{% endblock %}