techbangla/techbangla/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('techblog.urls')),
    path('account/', include('techuser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techbangla/techblog/urls.py
from django.urls import path
from techblog import views

app_name = 'tech_blog'

urlpatterns = [
    path('', views.IndexBlogView.as_view(), name='index'),
    path('blog-content/<slug:slug_name>', views.BlogView.as_view(), name='blog-content'),
    path('add-new/', views.AddNewView.as_view(), name='add-new'),
    path('edit-blog/<slug:slug_name>', views.EditBlogView.as_view(), name='edit-blog'),
    path('all/<name>/', views.AllBlogsView.as_view(), name='all-blogs'),
    path('like/<slug:slug_name>/', views.LikeView, name='like'),
]

techbangla/techuser/urls.py
from django.urls import path
from techuser import views

app_name = "tech_user"

urlpatterns = [
    path('', views.ownprofile, name='ownprofile'),
    path('authorprofile/<username>', views.authorprofile, name='authorprofile'),
    path('registration/', views.registrationview, name='registration'),
    path('login/', views.loginview, name='login'),
    path('logouturl/', views.logoutview, name='logouturl'),
    path('user-settings/', views.settingsview, name='user-settings'),
    path('basic-settings/', views.basicsetting, name='basic-settings'),
    path('other-settings/', views.othersetting, name='other-settings'),
    path('profilepic-settings/', views.addprofilepic, name='profilepic-settings'),
    path('passchange/', views.changepass, name='passchange'),
]

techbangla/techuser/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pic', verbose_name="Profile Picture", blank=True)
    about = models.TextField(verbose_name="About Yourself", blank=True)
    website = models.URLField(verbose_name="Website/Blogs", blank=True)
    facebook = models.URLField(verbose_name="Facebook Link", blank=True)
    twitter = models.URLField(verbose_name="Twitter Link", blank=True)
    linkedin = models.URLField(verbose_name="LinkedIn Link", blank=True)
    github = models.URLField(verbose_name="Github Link", blank=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}\'s About'

techbangla/techuser/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from techuser.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Email Address",
                             widget=forms.TextInput(attrs={'placeholder': "example@email.com"}))
    last_name = forms.CharField(required=True, label="Last Name",
                                widget=forms.TextInput(attrs={'placeholder': "Last Name"}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': "First Name"}),
            'username': forms.TextInput(attrs={'placeholder': "username"}),
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class UserBasicChange(forms.ModelForm):
    email = forms.EmailField(required=True, label="Email Address",
                             widget=forms.TextInput(attrs={'placeholder': "example@email.com"}))
    last_name = forms.CharField(required=True, label="Last Name",
                                widget=forms.TextInput(attrs={'placeholder': "Last Name"}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class UserBasicChange2(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic', 'about', 'website', 'facebook', 'twitter', 'linkedin', 'github',)


class UserBasicChange3(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

techbangla/techuser/views.py
'''from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, ListView, RedirectView
from techuser.forms import RegistrationForm
from django.contrib.auth.models import User
from techuser.models import UserProfile
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


# Create your views here.
# Decorator
def login_executed(redirect_to):
    """This Decorator kicks authenticated user out of a view"""

    def _method_wrapper(view_method):
        def _arguments_wrapper(request, *args, **kwargs):
            if request.user.is_authenticated:
                return redirect(redirect_to)
            return view_method(request, *args, **kwargs)

        return _arguments_wrapper

    return _method_wrapper


# Registration Class Based
class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'registration.html'
    success_url = reverse_lazy("tech_blog:index")

    def form_valid(self, form):
        valid = super(RegistrationView, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user)
        return valid


# Registration Functional
# @login_executed('tech_user:author-profile')
# def registrationview(request):
#     form = RegistrationForm()
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('tech_blog:index'))
#     data = {
#         'form': form,
#     }
#     return render(request, 'registration.html', context=data)


@login_executed('tech_user:author-profile')
def loginview(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)

            if user:
                if user:
                    login(request, user)
                    # print('Ok')
                    return HttpResponseRedirect(reverse('tech_blog:index'))
                else:
                    print("Account not active")
            else:
                print("Login Details Wrong")
    data = {
        'form': form,
    }
    return render(request, 'login.html', context=data)


#
# class LoginView(CreateView):
#     form_class = AuthenticationForm
#     template_name = 'login.html'
#     success_url = reverse_lazy('tech_blog:index')

# Logout Class Based
# class LogoutView(RedirectView):
#     # url = 'account/login/'
#     def get(self, request, *args, **kwargs):
#         logout(request)
#         return super(LogoutView, self).get(request, *args, **kwargs)


# Logout Functional
@login_required
def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('tech_blog:index'))


# class ProfileView(DetailView):
#     model = UserProfile
#     context_object_name = "userprofile"
#     template_name = 'user-profile.html'
#     slug_field = 'pk'


def profileview(request, user_name):
    user = User.objects.get(username=user_name)
    user_profile = UserProfile.objects.get(user=user.pk)
    context = {
        'user': user,
        'user_profile': user_profile,
    }
    return render(request, 'user-profile.html', context)
'''

from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from techuser.models import UserProfile
from techuser.forms import RegistrationForm, UserBasicChange, UserBasicChange2, UserBasicChange3


# Create your views here.
# Decorator
def login_executed(redirect_to):
    """This Decorator kicks authenticated user out of a view"""

    def _method_wrapper(view_method):
        def _arguments_wrapper(request, *args, **kwargs):
            if request.user.is_authenticated:
                return redirect(redirect_to)
            return view_method(request, *args, **kwargs)

        return _arguments_wrapper

    return _method_wrapper


@login_executed('tech_blog:index')
def registrationview(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse_lazy('tech_blog:index'))
    context = {
        'form': form,
    }
    return render(request, 'registration.html', context)


@login_executed('tech_blog:index')
def loginview(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        username, password = request.POST.get('username'), request.POST.get('password')
        if user := authenticate(username=username, password=password):
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('tech_blog:index'))
    context = {
        'form': form,
    }
    return render(request, 'login.html', context)


@login_required
def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('tech_blog:index'))


@login_required
def ownprofile(request):
    blogs = User.objects.all()
    return render(request, 'user-profile.html', context={'blogs': blogs})


@login_required
def settingsview(request):
    context = {

    }

    return render(request, 'settings.html', context)

@login_required
def basicsetting(request):
    current_user = request.user
    # form = RegistrationForm(instance=request.user)
    form = UserBasicChange(instance=current_user)
    if request.method == 'POST':
        form = UserBasicChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserBasicChange(instance=current_user)
            return HttpResponseRedirect(reverse('tech_user:ownprofile'))
    context = {
        'form': form,
    }

    return render(request, 'basic-info.html', context)

@login_required
def othersetting(request):
    current_user = request.user
    form = UserBasicChange2(instance=current_user.user_profile)
    if request.method == 'POST':
        form = UserBasicChange2(request.POST, request.FILES, instance=current_user.user_profile)
        if form.is_valid():
            form.save()
            # user_obj.user = current_user
            # user_obj.save()
            form = UserBasicChange2(instance=current_user.user_profile)
            return HttpResponseRedirect(reverse('tech_user:ownprofile'))
    context = {
        'form': form
    }

    return render(request, 'basic-info.html', context)


@login_required
def addprofilepic(request):
    current_user = request.user
    form = UserBasicChange3()
    if request.method == 'POST':
        form = UserBasicChange3(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = current_user
            user_obj.save()
            return HttpResponseRedirect(reverse('tech_user:ownprofile'))
    context = {
        'form': form
    }

    return render(request, 'basic-info.html', context)

@login_required
def changepass(request):
    form = PasswordChangeForm(request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tech_user:ownprofile'))
    context = {
        'form': form,
    }
    return render(request, 'basic-info.html', context)


def authorprofile(request, username):
    author = User.objects.get(username=username)
    blogs = User.objects.all()
    context = {
        'author': author,
        'blogs': blogs,
    }
    return render(request, 'author-profile.html', context)

techbangla/techuser/templates/author-profile.html
{% extends "base.html" %}
{% block title_block %}Profile{% endblock %}
{% load static %}
{% load my_filter %}
{% block body_block %}

    <div class="text-center d-flex align-items-center justify-content-center flex-column">
        {% if author.user_profile.profile_pic %}
            <img src="{{ author.user_profile.profile_pic.url }}" class="rounded-circle" width="200" height="200" alt="">
        {% else %}
            <img src="{% static "images/fox.jpg" %}" class="rounded-circle" width="200" height="200" alt="">
        {% endif %}
        <br>
        <h2><b>{{ author.first_name }} {{ author.last_name }}</b></h2>
        <br>
        <p class="">{{ author.user_profile.about }}</p>
        <br>
        <div class="">
            <a href="{{ author.user_profile.website }}" class="mx-1"><i class="fal fab fa-globe-asia"></i></a>
            <a href="{{ author.user_profile.facebook }}" class="mx-1"><i class="fab fa-facebook-f"></i></a>
            <a href="{{ author.user_profile.twitter }}" class="mx-1"><i class="fab fa-twitter"></i></a>
            <a href="{{ author.user_profile.linkedin }}" class="mx-1"><i class="fab fa-linkedin"></i></a>
            <a href="{{ author.user_profile.github }}" class="mx-1"><i class="fab fa-github"></i></a>
        </div>
    </div>
    <div class="d-flex align-items-center justify-content-center">
        <div class="grid">
            {% for blog in blogs %}
                {% if blog == author %}
                    {% for b in blog.user_blog.all %}
                        <div class="blog">
                <div class="blog-img">
                    <img src="{{ b.blogimg.url }}" alt="" class="img-fluid">
                </div>
                <br>
                <div class="tag d-flex">
                    <a href="{% url "tech_blog:all-blogs" name=b.category.category_name|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ b.category.category_name }}</b></h6>
                    </a>
                    <span>&nbsp; &nbsp;</span>
                    <a href="{% url "tech_blog:all-blogs" name=b.sub_category.subcategory_name|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ b.sub_category.subcategory_name }}</b></h6>
                    </a>
                </div>
                <br>
                <a href="{% url "tech_blog:blog-content" slug_name=b.slug %}">
                    <h5>{{ b.blogtitle }}</h5>
                </a>
                <div class="blog-summery">
                    <p>{{ b.blogcontent|range_filter }}
                        <a href="{% url "tech_blog:blog-content" slug_name=b.slug %}">Read More...</a></p>
                </div>
            </div>
                    {% endfor %}
                {% endif %}
            {% endfor %}


        </div>
    </div>

{% endblock %}

techbangla/techuser/templates/basic-info.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}Registration{% endblock %}
{% block body_block %}
    <div class="login-section">
        <div class="text-separation mb-5">
            <div class="text-separator-content border-bottom-2">
                <h3><b>LOGIN</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
        <br>
        <div class="login-form border border-1">

            <form class="p-4" method="POST" enctype="multipart/form-data">
                {{ form|crispy }}
                {{ form2|crispy }}
                {% csrf_token %}
                <div class="mt-3 d-md-flex align-items-center">
                    <input type="submit" value="EDIT" class="btn login-btn">
                    <div class="sep"></div>
                </div>
            </form>
            <div class="px-4">
                <a href="{% url "tech_user:passchange" %}"><p>Change Password</p></a>
            </div>
        </div>
    </div>
{% endblock %}

techbangla/techuser/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}Registration{% endblock %}
{% block body_block %}
    <div class="login-section">
        <div class="text-separation mb-5">
            <div class="text-separator-content border-bottom-2">
                <h3><b>LOGIN</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
        <br>
        <div class="login-form border border-1">
            <form class="p-4" method="POST">
{#                <label class="label" for="username">USERNAME</label>#}
{#                <input class="input-form" type="text" placeholder="username" name="username" id="username">#}
{#                <label class="label" for="password">PASSWORD</label>#}
{#                <input class="input-form" type="password" placeholder="password" name="password" id="password">#}
                {{ form|crispy }}
                {% csrf_token %}
                <div class="mt-3 d-md-flex align-items-center">
                    <input type="submit" value="LOGIN" class="btn login-btn">
                    <div class="sep"></div>
                    <label for="rememberme"><input type="checkbox" name="rememberme" id="rememberme">
                        <span>Remember Me</span></label>
                </div>
            </form>
            <div class="px-4">
                <a href=""><p>Lost Your Password?</p></a>
                <a href="{% url "tech_user:registration" %}"><p>New User?</p></a>
            </div>
        </div>
    </div>
{% endblock %}

techbangla/techuser/templates/not-neccesary-password-change.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}Registration{% endblock %}
{% block body_block %}
    <div class="login-section">
        <div class="text-separation mb-5">
            <div class="text-separator-content border-bottom-2">
                <h3><b>LOGIN</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
        <br>
        <div class="login-form border border-1">
            <form class="p-4" method="POST">
{#                <label class="label" for="username">USERNAME</label>#}
{#                <input class="input-form" type="text" placeholder="username" name="username" id="username">#}
{#                <label class="label" for="password">PASSWORD</label>#}
{#                <input class="input-form" type="password" placeholder="password" name="password" id="password">#}
                {{ form|crispy }}
                {% csrf_token %}
                <div class="mt-3 d-md-flex align-items-center">
                    <input type="submit" value="LOGIN" class="btn login-btn">
                    <div class="sep"></div>
                    <label for="rememberme"><input type="checkbox" name="rememberme" id="rememberme">
                        <span>Remember Me</span></label>
                </div>
            </form>
            <div class="px-4">
                <a href=""><p>Lost Your Password?</p></a>
                <a href="{% url "tech_user:registration" %}"><p>New User?</p></a>
            </div>
        </div>
    </div>
{% endblock %}

techbangla/techuser/templates/registration.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}Registration{% endblock %}
{% block body_block %}
<div class="login-section">
        <div class="text-separation mb-5">
            <div class="text-separator-content border-bottom-2">
                <h3><b>REGISTRATION</b></h3>
            </div>
            <div class="text-separator"></div>
        </div>
        <br>
        <div class="login-form border border-1">
            <form class="p-4" method="POST">
                {{ form|crispy }}
{#                <label class="label" for="firstname">FIRST NAME</label>#}
{#                <input class="input-form" type="text" placeholder="firstname" name="firstname" id="firstname">#}
{#                <label class="label" for="lastname">LAST NAME</label>#}
{#                <input class="input-form" type="text" placeholder="lastname" name="lastname" id="lastname">#}
{#                <label class="label" for="email">EMAIL</label>#}
{#                <input class="input-form" type="email" placeholder="email@mail.com" name="email" id="email">#}
{#                <label class="label" for="username">USERNAME</label>#}
{#                <input class="input-form" type="text" placeholder="username" name="username" id="username">#}
{#                <label class="label" for="password1">PASSWORD 1</label>#}
{#                <input class="input-form" type="password" placeholder="password1" name="password1" id="password1">#}
{#                <label class="label" for="password2">PASSWORD 2</label>#}
{#                <input class="input-form" type="password" placeholder="password2" name="password2" id="password2">#}
                {% csrf_token %}
                <div class="mt-3 d-md-flex align-items-center">
                    <input type="submit" value="REGISTER" class="btn login-btn">
                    <div class="sep"></div>
                </div>
            </form>
            <div class="px-4">
                <a href="{% url "tech_user:login" %}"><p>Already have an account?</p></a>
            </div>
        </div>
    </div>
{% endblock %}

techbangla/techuser/templates/settings.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}Registration{% endblock %}
{% block body_block %}
    <div class="setting-section">
        <div class="menu">
            <a href="{% url "tech_user:basic-settings" %}"><i class="fal fa-user-edit"></i> Basic Info</a>
        </div>
        {% if user.user_profile %}
        <div class="menu">
            <a href="{% url "tech_user:other-settings" %}"><i class="fal fa-edit"></i> Other Info</a>
        </div>
        {% else %}
        <div class="menu">
            <a href="{% url "tech_user:profilepic-settings" %}"><i class="fal fa-portrait"></i> Add Profile Picture</a>
        </div>
        {% endif %}
        <div class="menu">
            <a href="{% url "tech_user:passchange" %}"><i class="fal fa-user-secret"></i> Change Password</a>
        </div>
    </div>
{% endblock %}

techbangla/techuser/templates/user-profile.html
{% extends "base.html" %}
{% block title_block %}Profile{% endblock %}
{% load static %}
{% load my_filter %}
{% block body_block %}

    <div class="text-center d-flex align-items-center justify-content-center flex-column">
        {% if user.user_profile.profile_pic %}
            <img src="{{ user.user_profile.profile_pic.url }}" class="rounded-circle" width="200" height="200" alt="">
        {% else %}
            <img src="{% static "images/fox.jpg" %}" class="rounded-circle" width="200" height="200" alt="">
        {% endif %}
        <br>
        <h2><b>{{ user.first_name }} {{ user.last_name }}</b></h2>
        <br>
        <p class="">{{ user.user_profile.about }}</p>
        <br>
        <div class="">
            <a href="{{ user.user_profile.website }}" class="mx-1"><i class="fal fab fa-globe-asia"></i></a>
            <a href="{{ user.user_profile.facebook }}" class="mx-1"><i class="fab fa-facebook-f"></i></a>
            <a href="{{ user.user_profile.twitter }}" class="mx-1"><i class="fab fa-twitter"></i></a>
            <a href="{{ user.user_profile.linkedin }}" class="mx-1"><i class="fab fa-linkedin"></i></a>
            <a href="{{ user.user_profile.github }}" class="mx-1"><i class="fab fa-github"></i></a>
        </div>
    </div>
    <div class="d-flex align-items-center justify-content-center">
        <div class="grid">
            {% for blog in blogs %}
                {% if blog == user %}
                    {% for b in blog.user_blog.all %}
                        <div class="blog">
                <div class="blog-img">
                    <img src="{{ b.blogimg.url }}" alt="" class="img-fluid">
                </div>
                <br>
                <div class="tag d-flex">
                    <a href="{% url "tech_blog:all-blogs" name=b.category.category_name|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ b.category.category_name }}</b></h6>
                    </a>
                    <span>&nbsp; &nbsp;</span>
                    <a href="{% url "tech_blog:all-blogs" name=b.sub_category.subcategory_name|lower|replacespace %}">
                        <h6 class="h6-slider"><b>{{ b.sub_category.subcategory_name }}</b></h6>
                    </a>
                </div>
                <br>
                <a href="{% url "tech_blog:blog-content" slug_name=b.slug %}">
                    <h5>{{ b.blogtitle }}</h5>
                </a>
                <div class="blog-summery">
                    <p>{{ b.blogcontent|range_filter }}
                        <a href="{% url "tech_blog:blog-content" slug_name=b.slug %}">Read More...</a></p>
                </div>
            </div>
                    {% endfor %}
                {% endif %}
            {% endfor %}


        </div>
    </div>

{% endblock %}